### ISSUE TITLE
Train+Predict Supported methods Tracking

### ISSUE THREAD

**Issue by chrisvrose** [hpcc-systems/HSQL#58]
Tracking issue for the current supported for TRAIN and PREDICT.

- [X] Linear Regression
- [X] (Classification) Random Forest
- [x] (Regression) Random Forest
- [x] Binomial Logistic Regression
- [x] KMeans
- [X] GLM
  - [X] poisson
  - [X] gaussian
  - [X] gamma
  - [X] Binomial

## Further looking into

- [x] DBScan
